DROP TABLE AGE_LIMIT;
DROP TABLE AUTHOR_BOOK;
DROP TABLE BOOK_TYPE;
DROP TABLE GENRE_BOOK;
DROP TABLE GENRES;
DROP TABLE INVENTORY_NUMBER;
DROP TABLE ISSUANCE_LOG;
DROP TABLE PUBLISHING_HOUSE;
DROP TABLE READER_RATING;
DROP TABLE SERVICE_CATEGORY;
DROP TABLE TAGS;
DROP TABLE TAGS_BOOK;
DROP TABLE AUTHOR;
DROP TABLE LIBRARY_CARD;
DROP TABLE BOOKS;
DROP TABLE "ROLES";

/*DELETE FROM LIBRARY_CARD
WHERE NAME_READERS = 'Антон';*/