DROP TABLE BOOK_TYPE;
DROP TABLE READER_RATING;
DROP TABLE GENRES;
DROP TABLE "ROLES";
DROP TABLE TAGS;
DROP TABLE AUTHOR;
DROP TABLE SERVICE_CATEGORY;
DROP TABLE AGE_LIMIT;
DROP TABLE PUBLISHING_HOUSE;

DROP TABLE BOOKS;
DROP TABLE INVENTORY_NUMBER;
DROP TABLE LIBRARY_CARD;
DROP TABLE ISSUANCE_LOG;

DROP TABLE GENRE_BOOK;
DROP TABLE TAGS_BOOK;
DROP TABLE AUTHOR_BOOK;


DROP VIEW ALL_BOOKS_FOR_DELIVERY;
DROP VIEW TOP_10_BOOKS;
DROP VIEW TOP_10_READERS;

DROP SEQUENCE books_seq;

/*DELETE FROM LIBRARY_CARD
WHERE NAME_READERS = 'Антон';*/