/*��������� books*/
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (1, '����� � ���', 1, 20, 1, 1500);
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (2, '����� � ���', 2, 19, 1, 1400);
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (3, '����� � ���', 3, 18, 1, 1300);
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (4, '����� � ���', 4, 17, 1, 1200);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (5, '������ ����������', 10, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (6, '������ ����������', 9, 2, 900);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (7, '������ ����������', 8, 2, 1100);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (8, '������ ����������', 7, 2, 1200);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (9, '������ ����������', 6, 2, 1300);
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (10, '����� ���. � 2-� �����', 1, 5, 2, 900);
INSERT INTO BOOKS ("id", NAME_BOOK, TOM, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (11, '����� ���. � 2-� �����', 2, 5, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (12, '���� � ����', 6, 2, 1200);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (13, '����� ������ �������', 7, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (14, '���� �� ���', 3, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (15, '�������������� �����', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (16, '�������� ���', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (17, '���� ��������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE)
    VALUES (18, '������� ������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (19, '������ ��������', 2, 2, 1000);
    
    
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (20, '������ ���-�� ����', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (21, '���� ������ ������. ������� ���������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (22, '������ �� �����������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (23, '������ � ������������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (24, '�����, ������ � ��������', 2, 2, 1000); 
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (25, '������� ������ ������� ���������.', 2, 2, 1000);   
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (26, '����� � �������� � ������', 2, 2, 1000);   
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (27, '���-���-��� ������', 2, 2, 1000);   
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (28, '��� ��������� � ���������', 2, 2, 1000);  
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (29, '������ � �������� ������� ���������', 2, 2, 1000);
INSERT INTO BOOKS ("id", NAME_BOOK, AMOUNT, ID_AGE_LIMIT, PRICE) 
    VALUES (30, '1000 ���������, ������ � ������', 2, 2, 1000);  
    
    
/*��������� AUTHOR*/
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (1, '�������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (2, '�����������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (3, '�������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (4, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (5, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (6, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (7, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (8, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (9, '�����');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (10, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (11, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (12, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (13, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (14, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (15, '���������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (16, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (17, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (18, '�����������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (19, '�������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (20, '����������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (21, '����');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (22, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (23, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (24, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (25, '����������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (26, '��������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (27, '�����');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (28, '�������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (29, '������');
INSERT INTO AUTHOR ("id", AUTHOR) VALUES (30, '������');

/*��������� AUTHOR_BOOK*/
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (1, 1, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (2, 2, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (3, 3, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (4, 4, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (5, 5, 2);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (6, 6, 2);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (7, 7, 2);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (7, 8, 2);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (8, 9, 2);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (9, 10, 3);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (10, 11, 3);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (11, 12,4);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (12, 13, 5);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (13, 14, 6);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (14, 15, 7);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (15, 16, 8);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (16, 17, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (17, 18, 10);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (18, 19, 9);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (19, 20, 11);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (20, 20, 12);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (21, 21, 13);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (22, 21, 14);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (23, 22, 15);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (24, 22, 16);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (25, 23, 17);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (26, 23, 18);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (27, 24, 19);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (28, 24, 20);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (29, 25, 21);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (30, 25, 22);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (31, 26, 23);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (32, 26, 24);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (33, 27, 1);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (34, 27, 10);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (35, 28, 25);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (36, 28, 26);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (37, 29, 27);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (38, 29, 28);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (39, 30, 29);
INSERT INTO AUTHOR_BOOK ("id", ID_BOOK, ID_AUTHOR) VALUES (40, 30, 30);
    
/*��������� PUBLISHING_HOUSE*/ 
INSERT INTO PUBLISHING_HOUSE VALUES (1, '�����');
INSERT INTO PUBLISHING_HOUSE VALUES (2, '����');
INSERT INTO PUBLISHING_HOUSE VALUES (3, '������������� ������');
INSERT INTO PUBLISHING_HOUSE VALUES (4, '�������� ����');
INSERT INTO PUBLISHING_HOUSE VALUES (5, '���');
INSERT INTO PUBLISHING_HOUSE VALUES (6, '������� �������');
INSERT INTO PUBLISHING_HOUSE VALUES (7, '�����');
INSERT INTO PUBLISHING_HOUSE VALUES (8, '�����-�����');
INSERT INTO PUBLISHING_HOUSE VALUES (9, '������');

/*��������� PUBLISHING_HOUSE_BOOK*/
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (1, 1, 5);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (2, 1, 6);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (3, 1, 7);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (4, 1, 8);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (5, 1, 9);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (6, 2, 1);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (7, 3, 2);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (8, 4, 3);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (9, 5, 4);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (10, 6, 10);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (11, 7, 11);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (12, 8, 12);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (13, 9, 13);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (14, 8, 14);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (15, 7, 15);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (16, 6, 16);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (17, 1, 17);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (18, 2, 18);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (19, 3, 19);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (20, 4, 20);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (21, 5, 21);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (22, 6, 22);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (23, 7, 23);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (24, 8, 24);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (25, 9, 25);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (26, 1, 26);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (27, 2, 27);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (28, 3, 28);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (29, 4, 29);
INSERT INTO PUBLISHING_HOUSE_BOOK VALUES (30, 5, 30);

/*��������� LIBRARY_CARD*/
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (1, '�����', '�����', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (2, '������', '����', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (3, '�����', '�����', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (4, '��������', '���������', 100, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (5, '������', '����������', 200, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (6, '�������', '������', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (7, '������', '���������', 300, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (8, '������', '�����', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (9, '�������', '��������', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (10, '�������', '����', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (11, '�����', '���������', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (12, '�������', '�������', 0, 1);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (13, '���������', '��������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (14, '�������', '��������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (15, '���������', '����������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (16, '������', '��������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (17, '�������', '��������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (18, '�������', '���������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (19, '�����', '�������', 0, 2);
INSERT INTO LIBRARY_CARD ("id", NAME_READERS, SURNAME_READERS, SUM_FINES, ID_ROLE) 
    VALUES (20, '�������', '�����', 0, 2);

/*��������� ROLES*/
INSERT INTO "ROLES" VALUES (1, '������');
INSERT INTO "ROLES" VALUES (2, '��������� ����������');





























    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    