@startuml

autonumber
actor "Адм. доставки" as ADM
participant SPA
participant API
database DataBase as db
participant "Модуль\n'Заказы'" as ORD #aqua
participant "Справочник\n'DaData'" as DD #99FF99
participant "Модуль\n'Расписание работы\nсотрудников и \nрасчет зарплаты'" as A #aqua

activate ADM
ADM -> SPA: Создать заказ доставки
activate SPA
SPA -> API: Дай форму для заполнения \nданными клиента
activate API
SPA <-- API: Держи форму для заполнения
deactivate API
SPA --> ADM: Заполни форму \nданными о клиенте
deactivate SPA
ADM -> SPA: Получи телефон клиента
note right: как только поле с номером заполнилось
activate SPA
SPA -> API: Проверь телефон клиента
activate API
API -> db: найди клиента по номеру
activate db
alt Если клиент с таким номером уже есть
    db --> API: Получи данные клиента
    deactivate db
    API --> SPA: Вот данные клиента \nдля автозаполнения
    deactivate API
    SPA --> ADM: Получи данные клиента \nс этим номером телефона
end
ADM -> SPA: Получи адрес клиента
SPA -> DD: Проверь адрес на существование по справочнику
activate DD #99FF99
DD --> SPA: Данные из справочника
deactivate DD
SPA --> ADM: Получи совпадения адресов


ADM -> SPA: Подтверждаю данные \nи отправляю форму
SPA -> API: Вот данные клиента
activate API

API -> db: Дай мне адрес ресторана \nиз этого района
activate db
db --> API: Получи адрес ресторана
deactivate db
API -> db: В этом ресторане открыт \nпакет заказов?
activate db
alt Если пакет заказов НЕ ОТКРЫТ!!!
    db --> API: Нет открытого пакета заказов
    deactivate db
    API -> A: Дай мне список курьеров в этом ресторане
    activate A #aqua
    API <-- A: Сегодня на смене эти курьеры
    deactivate A
    API -> db: Дай мне данные о загруженности \nэтих курьеров
    activate db
    db --> API: Получи данные о курьерах
    deactivate db
    API -> API: Выбираем курьера
    API -> db: Создай пакет заказов и \nзаказ доставки
    activate db
    db --> API: Получи id заказа доставки
    deactivate db
else Если пакет заказов открыт
    API -> db: Создай заказ доставки и \nвложи в открытый пакет заказов
    activate db
    db --> API: Получи id заказа доставки
    deactivate db
end
note right of API: Переход в модуль "Заказы"
API -> ORD: Создай заказ для заказа доставки с этим id
activate ORD #aqua
ORD --> API: Перенаправление обратно в свой модуль
deactivate ORD
API -> ORD: Дай мне заказ с этим id заказа доставки
activate ORD #aqua
ORD --> API: Держи данные заказа с этим id заказа доставки
deactivate ORD
API -> db: Запиши данные с этим id заказа 
activate db
API <-- db: Получи все данные о заказе
deactivate db
API --> SPA: Получи данные о заказе
deactivate API
SPA--> ADM: Вот новый сформированный \nзаказ доставки
deactivate SPA
deactivate ADM

@enduml