DROP TABLE GENRE_BOOK;
DROP TABLE INVENTORY_NUMBER;
DROP TABLE ISSUANCE_LOG;
DROP TABLE SERVICE_CATEGORY;
DROP TABLE AUTHOR;
DROP TABLE LIBRARY_CARD;
DROP TABLE BOOKS;
DROP TABLE GENRES;
DROP TABLE "ROLES";
DROP TABLE TAGS;
DROP TABLE TAGS_BOOK;
DROP TABLE AGE_LIMIT;
DROP TABLE AUTHOR_BOOK;
DROP TABLE PUBLISHING_HOUSE;
DROP TABLE BOOK_TYPE;
DROP TABLE READER_RATING;



DROP SEQUENCE books_seq;

/*DELETE FROM LIBRARY_CARD
WHERE NAME_READERS = 'Антон';*/