
DROP TABLE AUTHOR_BOOK;
DROP TABLE GENRE_BOOK;
DROP TABLE TAGS_BOOK;

DROP TABLE ISSUANCE_LOG;
DROP TABLE LIBRARY_CARD;
DROP TABLE INVENTORY_NUMBER;
DROP TABLE BOOKS;


DROP TABLE AGE_LIMIT;
DROP TABLE SERVICE_CATEGORY;
DROP TABLE GENRES;
DROP TABLE "ROLES";
DROP TABLE TAGS;
DROP TABLE AUTHOR;
DROP TABLE PUBLISHING_HOUSE;
DROP TABLE BOOK_TYPE;
DROP TABLE READER_RATING;

PURGE RECYCLEBIN; 
COMMIT;
