
DROP TABLE AUTHOR_BOOK;
DROP TABLE GENRE_BOOK;
DROP TABLE TAGS_BOOK;

DROP TABLE ISSUANCE_LOG;
DROP TABLE LIBRARY_CARD;
DROP TABLE INVENTORY_NUMBER;
DROP TABLE BOOKS;


DROP TABLE AGE_LIMIT;
DROP TABLE SERVICE_CATEGORY;
DROP TABLE GENRES;
DROP TABLE "ROLES";
DROP TABLE TAGS;
DROP TABLE AUTHOR;
DROP TABLE PUBLISHING_HOUSE;
DROP TABLE BOOK_TYPE;
DROP TABLE READER_RATING;

PURGE RECYCLEBIN; 
COMMIT;

--DROP VIEW ALL_BOOKS_FOR_DELIVERY;
--DROP VIEW TOP_10_BOOKS;
--DROP VIEW TOP_10_READERS;
--
--DROP SEQUENCE AUTHOR_BOOK_SEQ;
--DROP SEQUENCE AUTHOR_SEQ;
--DROP SEQUENCE BOOK_TYPE_SEQ;
--DROP SEQUENCE BOOKS_SEQ;
--DROP SEQUENCE GENRE_BOOK_SEQ;
--DROP SEQUENCE GENRES_SEQ;
--DROP SEQUENCE INVENTORY_NUMBER_SEQ;
--DROP SEQUENCE LIBRARY_CARD_SEQ;
--DROP SEQUENCE PUBLISHING_HOUSE_SEQ;
--DROP SEQUENCE READER_RATING_SEQ;
--DROP SEQUENCE ROLE_SEQ;
--DROP SEQUENCE SERVICE_CATEGORY_SEQ;
--DROP SEQUENCE TAGS_BOOK_SEQ;
--DROP SEQUENCE TAGS_SEQ;
--DROP SEQUENCE AGE_LIMIT_SEQ;
--DROP SEQUENCE ISSUANCE_LOG_SEQ;