/*заполняем BOOK_TYPE*/
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Книга');
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Журнал');
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Газета');
    
/*заполняем READER_RATING*/
INSERT INTO READER_RATING (READER_RATING) VALUES (1);
INSERT INTO READER_RATING (READER_RATING) VALUES (2);
INSERT INTO READER_RATING (READER_RATING) VALUES (3);
INSERT INTO READER_RATING (READER_RATING) VALUES (4);
INSERT INTO READER_RATING (READER_RATING) VALUES (5);

/*заполняем SERVICE_CATEGORY*/
INSERT INTO SERVICE_CATEGORY (SERVICE_CATEGORY) VALUES ('Абонемент');
INSERT INTO SERVICE_CATEGORY (SERVICE_CATEGORY) VALUES ('Читальный зал');

/*заполняем AGE_LIMIT*/
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (0);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (6);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (12);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (16);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (18);

/*заполняем PUBLISHING_HOUSE*/ 
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Эксмо');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Речь');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Академический проект');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Классика речи');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('АСТ');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Молодая гвардия');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Литер');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Альфа-книга');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Родина');

/*заполняем GENRES*/
INSERT INTO GENRES (GENRE) VALUES ('Детектив');
INSERT INTO GENRES (GENRE) VALUES ('Триллер');
INSERT INTO GENRES (GENRE) VALUES ('Приключения');
INSERT INTO GENRES (GENRE) VALUES ('Авангардная литература');
INSERT INTO GENRES (GENRE) VALUES ('Боевик');
INSERT INTO GENRES (GENRE) VALUES ('Исторический роман');
INSERT INTO GENRES (GENRE) VALUES ('Роман');
INSERT INTO GENRES (GENRE) VALUES ('Мистика');
INSERT INTO GENRES (GENRE) VALUES ('Триллер/ужасы');
INSERT INTO GENRES (GENRE) VALUES ('Фантастика');
INSERT INTO GENRES (GENRE) VALUES ('Фэнтези');
INSERT INTO GENRES (GENRE) VALUES ('Сказки');

/*заполняем AUTHOR*/
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Толстой', 'Лев', 'Николаевич');
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Достоевский', 'Фёдор', 'Михайлович');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Шолохов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Тургенев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Лермонтов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Грибоедов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Макаренко');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Гоголь');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Чехов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Пушкин', 'Александр', 'Сергеевич');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Басова');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Минаев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Дашевская');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Кравченко');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Богатырёва');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Ключарёва');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Сазонова');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Ленковскаая');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Сладков');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Машковская');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Твен');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Джером');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Кухаркин');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Михалков');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Драгунский');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Крусанов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Бажов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Пришвин');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Тютчев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Есенин');

----------------------------------------------------------------------------------------
DECLARE 
    V_ID_BOOK           NUMBER;
    V_ID_AUTHOR         NUMBER;
    V_ID_GENRE          NUMBER;
BEGIN

/*заполняем книги с использованием переменных*/
INSERT INTO books (
    name_book,
    tom,
    id_age_limit,
    price,
    id_book_type,
    id_publishing_house,
    year_of_publishing
) VALUES (
    'Война и мир',
    1,
    1,
    1500,
    1,
    9,
    '01.01.1986'
)RETURNING "id" INTO v_id_book;

v_id_author := 1;

INSERT INTO author_book (
   id_book,
   id_author
) VALUES (
   v_id_book,
   v_id_author
);

v_id_genre := 7;

INSERT INTO genre_book (
   id_book,
   id_genre
) VALUES (
   v_id_book,
   v_id_genre
);




END;