/*заполняем BOOK_TYPE*/
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Книга');
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Журнал');
INSERT INTO BOOK_TYPE (BOOK_TYPE) VALUES ('Газета');

/*заполняем TAGS*/
INSERT INTO TAGS VALUES ('Война');
INSERT INTO TAGS VALUES ('Мир');
INSERT INTO TAGS VALUES ('Любовь');
INSERT INTO TAGS VALUES ('Россия');
INSERT INTO TAGS VALUES ('Крым');
INSERT INTO TAGS VALUES ('Франция');
INSERT INTO TAGS VALUES ('1812');
INSERT INTO TAGS VALUES ('Свадьба');
INSERT INTO TAGS VALUES ('День рождения');
INSERT INTO TAGS VALUES ('Новый год');
INSERT INTO TAGS VALUES ('Рождество');
INSERT INTO TAGS VALUES ('Толстой');
INSERT INTO TAGS VALUES ('Пушкин');
    
/*заполняем READER_RATING*/
INSERT INTO READER_RATING (READER_RATING) VALUES (1);
INSERT INTO READER_RATING (READER_RATING) VALUES (2);
INSERT INTO READER_RATING (READER_RATING) VALUES (3);
INSERT INTO READER_RATING (READER_RATING) VALUES (4);
INSERT INTO READER_RATING (READER_RATING) VALUES (5);

/*заполняем SERVICE_CATEGORY*/
INSERT INTO SERVICE_CATEGORY (SERVICE_CATEGORY) VALUES ('Абонемент');
INSERT INTO SERVICE_CATEGORY (SERVICE_CATEGORY) VALUES ('Читальный зал');

/*заполняем AGE_LIMIT*/
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (0);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (6);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (12);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (16);
INSERT INTO AGE_LIMIT (AGE_LIMIT) VALUES (18);

/*заполняем PUBLISHING_HOUSE*/ 
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Эксмо');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Речь');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Академический проект');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Классика речи');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('АСТ');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Молодая гвардия');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Литер');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Альфа-книга');
INSERT INTO PUBLISHING_HOUSE (PUBLISHING_HOUSE) VALUES ('Родина');

/*заполняем GENRES*/
INSERT INTO GENRES (GENRE) VALUES ('Детектив');
INSERT INTO GENRES (GENRE) VALUES ('Триллер');
INSERT INTO GENRES (GENRE) VALUES ('Приключения');
INSERT INTO GENRES (GENRE) VALUES ('Авангардная литература');
INSERT INTO GENRES (GENRE) VALUES ('Боевик');
INSERT INTO GENRES (GENRE) VALUES ('Исторический роман');
INSERT INTO GENRES (GENRE) VALUES ('Роман');
INSERT INTO GENRES (GENRE) VALUES ('Мистика');
INSERT INTO GENRES (GENRE) VALUES ('Триллер/ужасы');
INSERT INTO GENRES (GENRE) VALUES ('Фантастика');
INSERT INTO GENRES (GENRE) VALUES ('Фэнтези');
INSERT INTO GENRES (GENRE) VALUES ('Сказки');

/*заполняем AUTHOR*/
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Толстой', 'Лев', 'Николаевич');
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Достоевский', 'Фёдор', 'Михайлович');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Шолохов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Тургенев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Лермонтов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Грибоедов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Макаренко');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Гоголь');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Чехов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME, AUTHOR_FIRSTNAME, AUTHOR_PATRONYMIC) VALUES ('Пушкин', 'Александр', 'Сергеевич');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Басова');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Минаев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Дашевская');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Кравченко');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Богатырёва');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Ключарёва');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Сазонова');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Ленковскаая');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Сладков');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Машковская');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Твен');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Джером');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Кухаркин');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Михалков');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Драгунский');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Крусанов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Бажов');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Пришвин');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Тютчев');
INSERT INTO AUTHOR (AUTHOR_LASTNAME) VALUES ('Есенин');

----------------------------------------------------------------------------------------
DECLARE 
   V_ID_BOOK           NUMBER;
   V_ID_AUTHOR         NUMBER;
   V_ID_GENRE          NUMBER;
   V_ID_TAG            NUMBER;
BEGIN

/*заполняем книги с использованием переменных*/
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Война и мир', 1, 1, 1500, 1, 9, '01.01.1986') RETURNING "id" INTO v_id_book;

INSERT INTO AUTHOR_BOOK (ID_BOOK, ID_AUTHOR) VALUES (v_id_book, 1);
INSERT INTO GENRE_BOOK (ID_BOOK, ID_GENRE) VALUES (v_id_book, 7);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);

--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Война и мир', 2, 1, 1400, 1, 8, '01.01.1987') RETURNING "id" INTO v_id_book;

INSERT INTO AUTHOR_BOOK (ID_BOOK, ID_AUTHOR) VALUES (v_id_book, 1);
INSERT INTO GENRE_BOOK (ID_BOOK, ID_GENRE) VALUES (v_id_book,7);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Война и мир', 3, 1, 1300, 1, 7, '01.01.1988') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 1);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Война и мир', 4, 1, 1200, 1, 6, '01.01.1989') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 1);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Братья Карамазовы', 2, 1000, 1, 5, '01.01.1990') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 5);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Братья Карамазовы', 2, 900, 1, 4, '01.01.1991') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 5);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Братья Карамазовы', 2, 1100, 1, 3, '01.01.1992') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 5);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Братья Карамазовы', 2, 1200, 1, 2, '01.01.1993') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 5);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Братья Карамазовы', 2, 1300, 1, 1, '01.01.1994') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 5);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Тихий Дон. В 2-х томах', 1, 2, 900, 1, 2, '01.01.1995') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 3);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 9);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, TOM, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Тихий Дон. В 2-х томах', 2, 2, 1000, 1, 3, '01.01.1996') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 3);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 9);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Отцы и дети', 3, 1200, 1, 4, '01.01.1997') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 4);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 9);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Герой нашего времени', 5, 1000, 1, 5, '01.01.1998') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 9);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Горе от ума', 3, 1000, 1, 6, '01.01.1999') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 6);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 6);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 9);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Педагогическая поэма', 2, 1000, 1, 7, '01.01.2000') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 7);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Вишневый сад', 2, 1000, 1, 8, '01.01.2001') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 8);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,2);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Анна Каренина', 2, 1000, 1, 9, '01.01.2002') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 1);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Евгений Онегин', 2, 1000, 1, 8, '01.01.2003') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 10);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING)
   VALUES ('Судьба человека', 2, 1000, 1, 7, '01.01.2004') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 9);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Внутри что-то есть', 2, 1000, 1, 6, '01.01.2005') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 11);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 12);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Чуть правее сердца. Сборник рассказов', 2, 1000, 1, 5, '01.01.2006') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 13);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 14);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Никому не рассказывай', 2, 1000, 1, 4, '01.01.2007') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 15);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 16);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Письмо с подснежником', 2, 1000, 1, 5, '01.01.2008') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 17);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 18);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Стихи, сказки и рассказы', 2, 1000, 1, 6, '01.01.2009') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 19);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 20);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

--книги нет на складе!!!
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Сборник лучших смешных рассказов.', 2, 1000, 1, 3, '01.01.2010') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 21);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 22);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Стихи и рассказы о Родине', 2, 1000, 1, 2, '01.01.2011') RETURNING "id" INTO v_id_book;

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 23);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 24);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO BOOKS (NAME_BOOK, ID_AGE_LIMIT, PRICE, ID_BOOK_TYPE, ID_PUBLISHING_HOUSE, YEAR_OF_PUBLISHING) 
   VALUES ('Все-все-все сказки', 2, 1000, 1, 1, '01.01.2012');  

INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 25);
INSERT INTO author_book (id_book, id_author) VALUES (v_id_book, 26);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,5);
INSERT INTO genre_book (id_book, id_genre) VALUES (v_id_book,3);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 1);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 2);
INSERT INTO TAGS_BOOK (ID_BOOK, ID_TAG) VALUES (v_id_book, 3);

INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
INSERT INTO INVENTORY_NUMBER (ID_BOOK, ARRIVAL_BOOK, WRITE_OFF_DATE_BOOK) VALUES (v_id_book, '02.04.1995', NULL);
--------------------------------------------------------------------------------------------------------------------------



END;